- name: set selinux permissive to adm port.
  selinux:
    state: enforcing
    policy: targeted

- name: install haproxy package
  yum:
    name: haproxy
    state: present

- name: start haproxy service
  systemd:
    name: haproxy
    state: started
    enabled: yes

- name: open httpd service on firewalld
  firewalld:
    service: http
    permanent: yes
    state: enabled
    immediate: true

- name: open httpd service on firewalld
  firewalld:
    port: 81/tcp
    permanent: yes
    state: enabled
    immediate: true

- name: send the haproxy config file.
  template: 
    src: haproxy.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644
  register: haproxy_file

- name: restart haproxy service
  systemd:
    name: haproxy
    state: restarted
    enabled: yes
  when: haproxy_file.changed
