---
- name: all playbook
  hosts: webnodes
  serial: 1
  tasks:
  - haproxy:
      state: disabled
      host: '{{ inventory_hostname }}'
      backend: http_web
      socket: /var/run/haproxy.sock
      shutdown_sessions: true
    delegate_to: lb.acme.local

  - git:
      repo: 'http://192.168.122.194:81/root/tchelinux_passofundo.git'
      dest: /var/www/html
      clone: yes
      update: yes
      force: yes

  - haproxy:
      state: enabled
      host: '{{ inventory_hostname }}'
      backend: http_web
      socket: /var/run/haproxy.sock
      shutdown_sessions: true
    delegate_to: lb.acme.local
