- name: Install the RPM katello rpm file
  yum:
    name: http://{{ satellite_hostname }}/pub/katello-ca-consumer-latest.noarch.rpm
    state: present

- name: Registering host to the Satellite {{ satellite_hostname }}
  redhat_subscription:
    state: present
    activationkey: 'ak_rhel7_base_library'
    org_id: ACME
    auto_attach: true

- name: Install the katello agent rpm
  yum:
    name: katello-agent
    state: present

