- name: update host file
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ hostvars[item].ansible_fqdn }} {{ hostvars[item].ansible_hostname }}"
    state: present
  become: yes
  with_items: "{{ groups.all }}"

  lineinfile:
    dest: /etc/hosts
    line: "192.168.122.194 canes.acme.local canes"
    state: present
